apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: github-runner-deployment-autoscaler
  namespace: prod
spec:
  scaleTargetRef:
    # Your RunnerDeployment Here
    name: github-runners-deploy
    kind: RunnerDeployment
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    repositoryNames:
    - github-runner-on-aks
    - datascience
    - testing-workflows
    - github-runner-on-aks
    - rasa_chatbots
